blog/urls.py
from django.urls import path
from .views import BlogHomePageView, PostDetailView

app_name = 'blog'

urlpatterns = [
    path('', BlogHomePageView.as_view(), name='blog'),
    path('<slug:slug>/', PostDetailView.as_view(), name='post-detail')
]

server/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import HomePageView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', HomePageView.as_view(), name='home'),
    path('blog/', include('blog.urls'), name='blog')
]

blog/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone

class Category(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name


class Post(models.Model):
    
    class postObjects(models.Manager):
        def get_queryset(self):
            return super().get_queryset().filter(status='published')

    options = (
        ('published', 'Published'),
        ('draft', 'Draft'),
    )

    category = models.ForeignKey(
        Category, 
        on_delete=models.PROTECT,
        default=1
    )
    title = models.CharField(max_length=255)
    excerpt = models.TextField(null=True)
    content = models.TextField()
    slug = models.SlugField(
        unique_for_date='published', 
        null=False, 
        unique=True
    )
    published = models.DateTimeField(default=timezone.now)
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='blog_posts')
    status = models.CharField(max_length=10, choices=options, default='draft')
    
    objects = models.Manager()
    postobjects = postObjects()
    
    class Meta:
        ordering = ('-published',)
    
    def __str__(self) -> str:
        return f'{self.title} by - {self.author}'

        
class Comment(models.Model):
    
    post = models.ForeignKey(
        Post, 
        on_delete=models.CASCADE, 
        related_name='comments'
    )
    name = models.CharField(
        max_length=50
    )
    email = models.EmailField()
    content = models.TextField()
    publish = models.DateTimeField(auto_now_add=True)
    status = models.BooleanField(default=True)
    
    class Meta:
        ordering = ('publish',)
        
        def __str__(self):
            return f'Comment by - {self.name}'
        
    

blog/views.py
from django.shortcuts import render
from django.views.generic import TemplateView, DetailView
from .models import Post

# Create your views here.
class BlogHomePageView(TemplateView):
    template_name = 'blog/blog.html'
    
    def get_context_data(self, **kwargs) :
        context = super().get_context_data(**kwargs)
        context['posts'] = Post.postobjects.all()
        return context
    
    
class PostDetailView(DetailView):
    model = Post
    template_name = 'blog/post-detail.html'
    
    context_object_name = 'post'
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        post = Post.postobjects.filter(slug=self.kwargs.get('slug'))
        return context

server/views.py
from django.views.generic import TemplateView

class HomePageView(TemplateView):
    template_name = './home/home.html'

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Hosaik {% block title %} {% endblock %}</title>
</head>
<body>


    {% block content %}
    
    {% endblock %}
</body>
</html>

templates/blog/blog.html
{% extends "../base.html" %}

{% block title %} Blog {% endblock %}

{% block content %}

    {% for post in posts %}
        <a href="{% url 'blog:post-detail' slug=post.slug %}">
            <h2>{{post.title}}</h2>

            <p>{{post.excerpt |truncatechars:50}}</p>
        </a>
    
    {% endfor %}

{% endblock  %}

templates/blog/post-detail.html
{% extends "../base.html" %}

{% block content %}
Post detail view

{{post.title}}
{{post.content|truncatechars:50}}
{% endblock  %}

templates/home/home.html
{% extends "../base.html" %}

{% block title %} Home {% endblock %}

{% block content %}

    <h1>Home</h1>

    <a href="{% url 'blog:blog' %}">Blog</a>

{% endblock  %}